export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    PHP: "PHP",
    MySQL: "MySQL",
    bootstrap: "Bootstrap",
    tsx: "TSX",
    tsxReact: "TSX React",
    tsxNext: "TSX Next",
    JAVA: "Java",
    SQLSever: "SQLServer",
    LARAVEL: "Laravel",
    java: "Java",
    spring: "Spring",
    springboot: "Spring Boot",
    Giao_tiếp_hiệu_quả: "Giao tiếp hiệu quả",
    Lắng_nghe_tích_cực: "Lắng nghe tích cực",
    Hợp_tác_và_hỗ_trợ_đồng_đội: "Hợp tác và hỗ trợ đồng đội",
    Quản_lý_thời_gian: "Quản lý thời gian",
    TypeScript: "TypeScript",
    API: "API",
    ReactNative: "React Native",
}